"""Python interview cheatsheet.

Read numbered sections in order or open one source topic in this folder alongside 0_cheatsheet.*.
Examples target modern Python 3 and explain non-basic syntax locally.

Code generated by scripts/generate-cheatsheets.mjs; DO NOT EDIT.
Source: manifest-ordered topic files in this directory (excluding this file).
Edit the numbered files, then run: npm run cheatsheets:generate
"""

from __future__ import annotations

# ruff: noqa: E402, F401, F811, F841
# pyright: reportUnusedImport=false, reportUnusedVariable=false

import bisect
import collections
import collections.abc
import dataclasses
import functools
import heapq
import itertools
import math
import operator
import queue
import re
import sys

# ====================================================================
# 1. Version / Syntax Quick Map
# ====================================================================

"""
Python 3.8+:  walrus `:=`, `int.bit_count()`
Python 3.9+:  `list[int]`, `dict[str, int]`, `dict_a | dict_b`,
`@cache`
Python 3.10+: `int | None`, `match/case`, `itertools.pairwise`

Older equivalents:
    list[int]        -> typing.List[int]
    dict[str, int]   -> typing.Dict[str, int]
    int | None       -> typing.Optional[int]
    @cache           -> @lru_cache(maxsize=None)

`from __future__ import annotations` must appear before ordinary
imports. Every numbered file and the generated aggregate place it
there so cross-topic type hints are not evaluated immediately.
Quoted forward references also remain safe when copied without the
future import.
"""

# ====================================================================
# 2. Common Imports
# ====================================================================

"""
collections: collections.Counter, collections.defaultdict
heapq:       heapq.heappush, heapq.heappop, heapq.heapify
bisect:      bisect.bisect_left, bisect.bisect_right
functools:   functools.cache, functools.cmp_to_key
itertools:   itertools.pairwise, itertools.product
math:        math.gcd, math.lcm, math.isqrt, math.inf
dataclasses: dataclasses.dataclass, dataclasses.field
operator:    operator.itemgetter, operator.attrgetter
re:          re.findall, re.sub
"""

# ====================================================================
# 3. Python Data Structures - CRUD Cheat Sheet
# ====================================================================

"""
Python Data Structures - CRUD Cheat Sheet

Big naming logic:

| Concept          | Pattern                       |
|------------------|-------------------------------|
| Add one item     | append / add / heapq.heappush |
| Add many items   | extend / update               |
| Remove + return  | pop / popleft / heapq.heappop |
| Remove by value  | remove / discard / del        |
| Remove all       | clear                         |
| Contains?        | in                            |
| Soft read/delete | get / discard / pop(default)  |

Why the names stick:

- `pop*` means "take it out and give it back".
- `remove` / `discard` delete a known value.
- `del` / `pop(key)` delete a known dict key.
- `clear` empties the container.
- `in` is the universal membership test.

Master memory table:

Core containers:

| Operation       | list   | set            | dict          |
|-----------------|--------|----------------|---------------|
| Empty           | []     | set()          | {}            |
| Add one         | append | add            | d[k] = v      |
| Add many        | extend | update         | update        |
| Read            | lst[i] | x in s         | d[k] / get    |
| Remove + return | pop    | pop            | pop / popitem |
| Remove by value | remove | discard/remove | del / pop(k)  |
| Empty all       | clear  | clear          | clear         |

Priority and double-ended containers:

| Operation       | heapq          | collections.deque |
|-----------------|----------------|-------------------|
| Empty           | []             | collections.deque |
| Add one         | heapq.heappush | append/appendleft |
| Add many        | heapq.heapify  | extend/extendleft |
| Read            | heap[0]        | q[0] / q[-1]      |
| Remove + return | heapq.heappop  | pop / popleft     |
| Remove by value | rebuild        | remove            |
| Empty all       | clear          | clear             |

Mental model: `pop*` returns what it removes; `remove`, `discard`,
`del`, `clear`, `sort`, and `reverse` mutate and return None.
"""




# Shows list creation, indexing, copying, stack use, mutation, deletion, and their main costs.
def list_create_read_update_delete_examples(
    n: int, rows: int, cols: int, nums: list[int]
) -> None:
    x = 2

    # CREATE
    lst: list[int] = []  # Empty dynamic array / stack.
    from_iterable = list(nums)
    zeros = [0] * n
    one_to_n = list(range(1, n + 1))

    # Matrix create: make fresh inner lists.
    grid = [[0] * cols for _ in range(rows)]
    visited = [[False for _ in range(cols)] for _ in range(rows)]
    bad_grid = [[0] * cols] * rows  # AVOID: every row aliases.

    # READ
    first = nums[0]  # IndexError if empty.
    last = nums[-1]
    middle = nums[1:3]  # Slice returns a new shallow list.
    size = len(nums)
    contains_x = x in nums
    first_x = nums.index(x) if x in nums else -1
    count_x = nums.count(x)

    # COPY: all are shallow for a flat list.
    copy1 = nums[:]
    copy2 = nums.copy()
    copy3 = list(nums)
    matrix_copy = [row[:] for row in grid]

    # UPDATE / ADD
    lst.append(x)  # Add one to the right end.
    lst.extend([4, 5])  # Add many to the right end.
    lst.insert(1, x)  # Insert before index 1.
    nums[0] = 99
    nums.sort()  # In-place; returns None.
    nums.reverse()  # In-place; returns None.
    sorted_nums = sorted(nums)  # New list.
    reversed_nums = nums[::-1]  # New list.

    # DELETE
    removed_last = lst.pop()  # Remove and return last item.
    removed_at_index = lst.pop(0)  # O(n): shifts everything left.
    if x in lst:
        lst.remove(x)  # Remove first matching value; returns None.
    del lst[:1]  # Delete by index/slice.
    lst.clear()

    # Stack pattern: right end only, O(1).
    stack: list[int] = []
    stack.append(1)
    top = stack[-1]
    popped = stack.pop()


# Shows set creation, membership, algebra, updates, deletion, and hashable tuple keys.
def set_create_read_update_delete_examples(nums: list[int], grid: list[list[int]]) -> None:
    x = 2

    # CREATE
    s: set[int] = set()  # Empty set. `{}` is an empty dict.
    from_iterable = set(nums)
    with_data = {1, 2, 3}

    # READ
    exists = x in with_data  # Average O(1); sets have no indexing.
    size = len(with_data)

    # UPDATE / ADD
    s.add(x)  # Add one.
    s.update([3, 4, 5])  # Add many from any iterable.
    union = {1, 2} | {2, 3}
    intersection = {1, 2} & {2, 3}
    difference = {1, 2} - {2, 3}
    symmetric_difference = {1, 2} ^ {2, 3}

    # DELETE
    s.discard(x)  # Soft: no error if absent.
    # s.remove(x)  # Strict: KeyError if absent.
    arbitrary = s.pop() if s else None  # Remove and return any item.
    s.clear()

    # Tuple keys are hashable when all parts are hashable.
    visited: set[tuple[int, int]] = set()
    for r, row in enumerate(grid):
        for c, value in enumerate(row):
            if value:
                visited.add((r, c))


# Shows dictionary creation, strict and soft reads, grouping, counting, merging, and deletion.
# Requires: import collections
def dictionary_create_read_update_delete_examples(words: list[str], nums: list[int]) -> None:
    # CREATE
    d: dict[str, int] = {}
    with_data = {"a": 1, "b": 2}
    from_keywords = dict(a=1, b=2)
    from_pairs = dict(zip(["a", "b"], [1, 2]))

    # READ
    strict = with_data["a"]  # KeyError if missing.
    soft_none = with_data.get("missing")  # None if missing.
    soft_default = with_data.get("missing", 0)
    exists = "a" in with_data  # Tests keys, not values.
    size = len(with_data)
    keys = list(with_data.keys())
    values = list(with_data.values())
    pairs = list(with_data.items())

    # UPDATE / ADD
    d["c"] = 3  # Set or overwrite one key.
    d.update({"d": 4, "e": 5})  # Merge many; right side wins.
    merged_modern = {"a": 1} | {"a": 9, "b": 2}
    merged_old = {"a": 1}
    merged_old.update({"a": 9, "b": 2})

    # Grouping: setdefault is a dict method.
    groups1: dict[str, list[str]] = {}
    for w in words:
        groups1.setdefault("".join(sorted(w)), []).append(w)

    # defaultdict(<factory>): missing key creates factory().
    groups2: collections.defaultdict[str, list[str]]
    groups2 = collections.defaultdict(list)
    for w in words:
        groups2["".join(sorted(w))].append(w)

    counts1: dict[int, int] = {}
    for x in nums:
        counts1[x] = counts1.get(x, 0) + 1

    counts2: collections.defaultdict[int, int]
    counts2 = collections.defaultdict(int)
    for x in nums:
        counts2[x] += 1

    # Counter(<iterable>): frequency dict with 0 for missing keys.
    counts3 = collections.Counter(nums)
    top_three = counts3.most_common(3)
    counts3.update([10])
    counts3.subtract([10])
    counts3 += collections.Counter()  # Drop zero/negative counts.

    # DELETE
    removed_value = d.pop("c")  # KeyError if missing.
    removed_or_default = d.pop("missing", 0)
    last_pair = d.popitem()  # Remove and return last inserted pair.
    del with_data["a"]
    d.clear()


# Shows heap creation, minimum access, insertion, removal, replacement, and max-heap negation.
# Requires: import heapq
def heap_create_read_update_delete_examples(nums: list[int]) -> None:
    # CREATE
    heap: list[int] = nums[:]
    heapq.heapify(heap)  # Turn a list into a min-heap in-place, O(n).
    built_by_push: list[int] = []
    for x in nums:
        heapq.heappush(built_by_push, x)  # O(log n) each.

    # READ
    smallest = heap[0] if heap else None  # Peek; do not remove.
    size = len(heap)

    # UPDATE / ADD
    heapq.heappush(heap, 42)
    max_heap = [-x for x in nums]  # Python heapq is min-heap only.
    heapq.heapify(max_heap)
    largest = -heapq.heappop(max_heap)

    # DELETE
    removed_smallest = heapq.heappop(heap) if heap else None
    # No efficient remove-by-value: rebuild, or use lazy deletion
    # with a separate "deleted" counter in advanced problems.
    heap.clear()


# Shows double-ended queue operations for constant-time work at either end.
# Requires: import collections
def double_ended_queue_create_read_update_delete_examples(nums: list[int]) -> None:
    x = 2

    # CREATE
    q: collections.deque[int] = collections.deque()
    with_data = collections.deque(nums)
    bounded = collections.deque(maxlen=3)  # Auto-drops old items.

    # READ
    left = with_data[0] if with_data else None
    right = with_data[-1] if with_data else None
    size = len(with_data)
    contains_x = x in with_data

    # UPDATE / ADD
    q.append(1)  # Add right.
    q.appendleft(0)  # Add left.
    q.extend([2, 3])  # Add many to right.
    q.extendleft([-1, -2])  # Adds left one-by-one; order reverses.
    q.rotate(1)  # Move rightmost item to the left.

    # DELETE
    removed_right = q.pop()
    removed_left = q.popleft()
    if x in q:
        q.remove(x)  # Remove first matching value.
    q.clear()

    # Usage patterns:
    fifo = collections.deque([1])
    fifo.append(2)
    next_in_line = fifo.popleft()  # Queue: FIFO.

    stack = collections.deque([1])
    stack.append(2)
    top = stack.pop()  # Stack: LIFO.


# Shows synchronized FIFO, LIFO, and priority queues intended for communication between threads.
# Requires: import queue
def thread_safe_queue_create_read_update_delete_examples() -> None:
    # CREATE: for multi-threading; prefer deque/heapq in algorithms.
    fifo = queue.Queue()
    stack = queue.LifoQueue()
    priority = queue.PriorityQueue()

    # UPDATE / ADD
    fifo.put(1)
    stack.put(1)
    priority.put((0, "task"))

    # READ
    fifo_empty = fifo.empty()
    fifo_size = fifo.qsize()  # Approximate under concurrency.

    # DELETE
    fifo_item = fifo.get()
    stack_item = stack.get()
    priority_item = priority.get()

# ====================================================================
# 4. Copying / Binding / Mutability
# ====================================================================

# Contrasts shared bindings, shallow copies, nested aliasing, and safe matrix construction.
def copy_and_aliasing(grid: list[list[int]], nums: list[int]) -> None:
    alias = nums  # Same list object.
    shallow1 = nums[:]
    shallow2 = nums.copy()
    shallow3 = list(nums)

    matrix_shallow = grid[:]  # New outer list, shared rows.
    matrix_copy = [row[:] for row in grid]  # Common matrix copy.

    path: list[int] = []
    result: list[list[int]] = []
    result.append(path.copy())  # Save a snapshot in backtracking.
    # result.append(path)
    # AVOID: later path mutations affect saved row.

    # Mutable default args: avoid `def f(bucket=[]): ...`; use
    # None sentinel.

# ====================================================================
# 5. Sorting / Comparison / Heap
# ====================================================================

# Compares in-place sort, sorted copies, key functions, reverse order, and comparator adapters.
# Requires: import functools
# Requires: import operator
def sorting_patterns(
    items: list[tuple[str, int]], intervals: list[list[int]]
) -> None:
    nums = [3, 1, 2]

    new_sorted = sorted(nums)
    nums.sort()  # Mutates; returns None.

    desc_all = sorted(nums, reverse=True)

    # sorted(<list>, key=lambda <argument>: <representation
    # sorting key>)
    # <argument>: each element extracted from the list/iterable.
    # <representation sorting key>: value Python compares for
    # that element.
    by_start_end = sorted(intervals, key=lambda x: (x[0], x[1]))
    # x is one interval like [start, end]; (x[0], x[1]) sorts by
    # start, then end.

    score_desc_name_asc = sorted(
        items, key=lambda item: (-item[1], item[0])
    )
    # item is one tuple like (name, score); (-score, name) means
    # score desc, name asc.

    # Stable two-pass sort: sort secondary first, primary second.
    records = [("a", 90, 20), ("b", 90, 18)]
    records = sorted(
        records, key=lambda r: r[2]
    )  # r is each record; r[2] is age.
    records = sorted(
        records, key=lambda r: r[1], reverse=True
    )  # r[1] is score.
    records = sorted(
        records, key=operator.itemgetter(2)
    )  # same as lambda r: r[2]
    records = sorted(
        records, key=operator.itemgetter(1), reverse=True
    )  # same as lambda r: r[1]

    best = max(items, key=lambda item: (item[1], item[0]))
    worst = min(items, key=lambda item: item[1])

    # Comparator fallback: this is the -1/0/+1 style from Java/C/C++.
    # Python 3 sorting does not accept compare= directly; wrap
    # it with cmp_to_key.
    # compare returns negative, zero, or positive for ascending pairwise ordering.
    def compare(a: int, b: int) -> int:
        return (a % 2) - (b % 2) or a - b

    sorted_with_cmp = sorted(nums, key=functools.cmp_to_key(compare))




# Shows named key extractors, tuple keys, attribute keys, and legacy pairwise comparators.
# Requires: import functools
# Requires: import operator
def custom_sorting_patterns(
    words: list[str], transactions: list["TransactionRecord"]
) -> None:
    # 1) Lambda key: most common.
    # w is each string in words; (len(w), w) is the value used
    # for ordering.
    by_len_then_word = sorted(words, key=lambda w: (len(w), w))

    # 2) Named key function: easier to debug/explain when the
    # key is not tiny.
    # word_key sorts by increasing length and then alphabetical spelling.
    def word_key(word: str) -> tuple[int, str]:
        return len(word), word

    by_named_key = sorted(words, key=word_key)

    # 3) Comparator function: use only when "a before b?" logic
    # is naturally pairwise.
    # This function receives TWO items and returns negative /
    # zero / positive.
    # compare_words expresses the same ordering as word_key through pairwise comparison.
    def compare_words(a: str, b: str) -> int:
        if len(a) != len(b):
            return len(a) - len(b)
        return -1 if a < b else (1 if a > b else 0)

    by_comparator = sorted(
        words, key=functools.cmp_to_key(compare_words)
    )

    # 4) Custom object ordering: sorted(objs) calls obj.__lt__(other).
    by_time = sorted(transactions)
    by_time_key = sorted(
        transactions, key=operator.attrgetter("time")
    )  # same as lambda t: t.time

    # 5) Common accessors: itemgetter(0) is like lambda item: item[0].
    pairs = [("b", 2), ("a", 3)]
    by_first = sorted(pairs, key=operator.itemgetter(0))
    by_first_then_second = sorted(
        pairs, key=operator.itemgetter(0, 1)
    )


# TransactionRecord supplies __lt__ so ordinary sorting compares amount and then name.
class TransactionRecord:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, raw: str) -> None:
        name, time, amount, city = raw.split(",")
        self.name = name
        self.time = int(time)
        self.amount = int(amount)
        self.city = city
        self.raw = raw

    # Internal helper for lt.
    def __lt__(self, other: "TransactionRecord") -> bool:
        return (self.time, self.amount, self.city) < (
            other.time,
            other.amount,
            other.city,
        )

    # Internal helper for repr.
    def __repr__(self) -> str:
        return f"TransactionRecord({self.raw!r})"




# Shows binary-search insertion boundaries and maintaining an ascending list.
# Requires: import bisect
def bisect_patterns(sorted_nums: list[int], x: int) -> None:
    left = bisect.bisect_left(sorted_nums, x)  # First index >= x.
    right = bisect.bisect_right(
        sorted_nums, x
    )  # First index with value > x.
    count_x = right - left
    exists = left < len(sorted_nums) and sorted_nums[left] == x

    insert_at_left = bisect.bisect_left(sorted_nums, x)
    insert_at_right = bisect.bisect_right(sorted_nums, x)
    bisect.insort(
        sorted_nums, x
    )  # Finds position O(log n), inserts into list O(n).




# Shows minimum heaps, negated maximum heaps, tuple priorities, replacement, and merging.
# Requires: import heapq
def heap_patterns(
    nums: list[int], k: int, tasks: list[tuple[int, str]]
) -> None:
    # Basic heap CRUD lives in `heap_create_read_update_delete_examples`.
    # This section keeps the interview variants.

    # Top-k one-off helpers.
    k_largest = heapq.nlargest(k, nums)
    k_smallest = heapq.nsmallest(k, nums)

    # Bounded min-heap for streaming kth largest.
    top: list[int] = []
    for x in nums:
        heapq.heappush(top, x)
        if len(top) > k:
            heapq.heappop(top)

    # Tuple heap: priority, tie breaker, payload.
    priority_queue: list[tuple[int, int, str]] = []
    for order, (priority, name) in enumerate(tasks):
        heapq.heappush(priority_queue, (priority, order, name))

# ====================================================================
# 6. Iteration / Comprehensions / Ranges
# ====================================================================

# Shows ranges, enumerate, zip, pairwise iteration, comprehensions, generators, and unpacking.
# Requires: import itertools
def iteration_patterns(
    nums: list[int], a: list[int], b: list[int]
) -> None:
    for i, x in enumerate(nums):
        pass

    for i in range(len(nums)):
        pass

    for i in range(len(nums) - 1, -1, -1):
        pass

    pairs1 = list(itertools.pairwise(nums))  # Python 3.10+
    pairs2 = list(
        zip(nums, nums[1:])
    )  # Older equivalent; slice copies.

    zipped = list(zip(a, b))  # Stops at shortest input.
    dot = sum(x * y for x, y in zip(a, b))

    # [<output_expr> for <element> in <iterable> if
    # <filter_condition>]
    # x is each number from nums; x * x is what gets stored.
    squares = [x * x for x in nums if x >= 0]

    # Braces with one expression make a set comprehension.
    unique_mods = {x % 10 for x in nums}

    # Braces with key: value make a dict comprehension.
    # enumerate(nums) yields (index, value), unpacked as i, x.
    index_by_value = {x: i for i, x in enumerate(nums)}

    # Generator expression: no list is built; sum/any/all pull
    # values lazily.
    total_pos = sum(x for x in nums if x > 0)
    has_even = any(x % 2 == 0 for x in nums)
    all_positive = all(x > 0 for x in nums)

    # Star unpacking: middle becomes a list of the leftover values.
    first, *middle, last = nums if len(nums) >= 2 else [0, 0]
    a0, b0 = 1, 2
    a0, b0 = b0, a0

# ====================================================================
# 7. Strings / Numbers / Bits
# ====================================================================

# Shows common string creation, slicing, searching, joining, counting, and regular expressions.
# Requires: import collections
# Requires: import re
def string_patterns(
    s: str, chars: list[str], nums: list[int]
) -> None:
    # Split / join / trim.
    words = s.split()  # Split on runs of whitespace.
    csv_parts = [
        part.strip() for part in s.split(",") if part.strip()
    ]
    lines = s.splitlines()
    joined = " ".join(words)
    answer_line = ",".join(str(x) for x in nums)

    # Efficient build: list append + join.
    pieces: list[str] = []
    for ch in chars:
        pieces.append(ch)
    built = "".join(pieces)

    # Slices: end index is exclusive.
    first_three = s[:3]
    without_last = s[:-1]
    reversed_s = s[::-1]
    every_other = s[::2]

    # Search / replace.
    contains = "needle" in s
    first_idx = s.find("needle")  # -1 if absent.
    count_a = s.count("a")
    replaced_once = s.replace("old", "new", 1)
    replaced_all = s.replace("old", "new")

    # Case / whitespace.
    lower = s.lower()
    upper = s.upper()
    stripped = s.strip()
    left_stripped = s.lstrip()
    right_stripped = s.rstrip()
    starts = s.startswith("pre")
    ends = s.endswith("suf")

    # Character classes are common in palindrome / parsing problems.
    normalized = "".join(ch.lower() for ch in s if ch.isalnum())
    is_clean_palindrome = normalized == normalized[::-1]
    kind_flags = [
        (ch.isalpha(), ch.isdigit(), ch.isalnum(), ch.isspace())
        for ch in s[:3]
    ]

    # Ord / chr for compact fixed alphabet arrays.
    idx = ord("c") - ord("a")
    ch = chr(ord("a") + idx)
    digit = ord("7") - ord("0")
    freq26 = [0] * 26
    for ch2 in s:
        if "a" <= ch2 <= "z":
            freq26[ord(ch2) - ord("a")] += 1
    anagram_key_counts = tuple(freq26)
    anagram_key_sorted = "".join(sorted(s))
    char_counts = collections.Counter(s)
    top_chars = char_counts.most_common(3)

    # Parsing numbers from strings.
    ints_from_spaces = [int(part) for part in s.split()]
    ints_from_text = [int(m) for m in re.findall(r"-?\d+", s)]
    digits_from_string = [
        ord(ch) - ord("0") for ch in s if ch.isdigit()
    ]
    zero_padded = f"{len(s):04d}"  # Useful for labels/debug output.




# Shows integer conversion, exact square roots, number theory helpers, and bit operations.
# Requires: import math
def numeric_bit_patterns(a: int, b: int, n: int, mask: int) -> None:
    sign = (a > 0) - (a < 0)
    absolute = abs(a)
    clamped = max(0, min(n, 100))

    quotient, remainder = divmod(a, b)  # Same as (a // b, a % b).
    true_division = a / b
    floor_division = a // b  # Floors toward -inf.
    trunc_toward_zero = (abs(a) // abs(b)) * (1 if a * b >= 0 else -1)
    ceil_div_positive = -(-a // b)  # For positive b.
    remainder = a % b  # If b > 0, result is in [0, b).
    normalized_mod = (a % b + b) % b

    inf = float("inf")
    neg_inf = float("-inf")
    also_inf = math.inf

    gcd = math.gcd(a, b)
    lcm = math.lcm(a, b)
    root_floor = math.isqrt(n)
    is_square = root_floor * root_floor == n
    choose_two = math.comb(n, 2) if n >= 2 else 0
    permutations = math.perm(n, 2) if n >= 2 else 0

    mod = 10**9 + 7
    add_mod = (a + b) % mod
    mul_mod = (a * b) % mod
    pow_mod = pow(a, n, mod)
    # Modular inverse when gcd(a, mod) == 1.
    # inv_mod = pow(a, -1, mod)

    # Decimal digits.
    digits = [int(ch) for ch in str(abs(n))]
    digit_sum = sum(digits)
    x = abs(n)
    reversed_digits = 0
    while x:
        reversed_digits = reversed_digits * 10 + x % 10
        x //= 10

    one_bit = 1 << 3
    mask |= 1 << 3  # Set bit.
    has_bit = (mask & (1 << 3)) != 0
    mask &= ~(1 << 3)  # Clear bit.
    mask ^= 1 << 3  # Toggle bit.
    bits = mask.bit_count()

# ====================================================================
# 8. Functions / Scope / Decorators
# ====================================================================

# Shows positional, keyword, default, variadic positional, and variadic keyword arguments.
def function_call_syntax(
    required: int, *args: int, **kwargs: int
) -> None:
    collected_args = args  # tuple
    collected_kwargs = kwargs  # dict

    values = [1, 2, 3]
    options = {"required": 1}
    # function_call_syntax(*values)
    # function_call_syntax(**options)


# ScopeTreeNode is a minimal binary node for the nested-scope example below.
class ScopeTreeNode:
    # Local copy so this section does not depend on the Classes
    # section.
    # Initializes a new instance and establishes its invariants.
    def __init__(
        self,
        val: int = 0,
        left: "ScopeTreeNode | None" = None,
        right: "ScopeTreeNode | None" = None,
    ) -> None:
        self.val = val
        self.left = left
        self.right = right


# Shows nonlocal mutation: the nested traversal updates a binding in its enclosing function.
def nested_helper_and_nonlocal(root: ScopeTreeNode | None) -> int:
    count = 0

    # visit_connected_land marks every land cell connected to this cell.
    def visit_subtree(node: ScopeTreeNode | None) -> None:
        # nonlocal means "when assigning count, use the
        # count in the outer
        # function scope." Without it, count += 1 would
        # create/read a local name.
        nonlocal count
        if node is None:
            return
        count += 1
        visit_subtree(node.left)
        visit_subtree(node.right)

    visit_subtree(root)
    return count




# Demonstrates functools.cache memoization: repeated arguments reuse the stored return value.
# Requires: import functools
@functools.cache
def cached_dp(i: int, remaining: int) -> int:
    # @functools.cache means: cached_dp = functools.cache(cached_dp).
    # It memoizes by the argument tuple (i, remaining), so args
    # must be hashable.
    if remaining == 0:
        return 1
    if i == 0 or remaining < 0:
        return 0
    return cached_dp(i - 1, remaining) + cached_dp(
        i - 1, remaining - 1
    )




# Demonstrates lru_cache(maxsize=None), the pre-Python-3.9 spelling of unbounded memoization.
# Requires: import functools
@functools.lru_cache(maxsize=None)
def cached_dp_old_spelling(i: int) -> int:
    return (
        i
        if i <= 1
        else cached_dp_old_spelling(i - 1)
        + cached_dp_old_spelling(i - 2)
    )

# ====================================================================
# 9. Classes / Nodes / Dataclasses
# ====================================================================

# Singly linked-list node matching common interview problem definitions.
class ListNode:
    # Initializes a new instance and establishes its invariants.
    def __init__(
        self, val: int = 0, next: "ListNode | None" = None
    ) -> None:
        self.val = val
        self.next = next


# Binary-tree node matching common interview problem definitions.
class TreeNode:
    # Initializes a new instance and establishes its invariants.
    def __init__(
        self,
        val: int = 0,
        left: "TreeNode | None" = None,
        right: "TreeNode | None" = None,
    ) -> None:
        self.val = val
        self.left = left
        self.right = right




# Interval is a closed numeric range from start through end.
# Requires: import dataclasses
@dataclasses.dataclass
class Interval:
    # @dataclasses.dataclass reads fields and generates __init__,
    # __repr__, __eq__.
    start: int
    end: int




# Point is an immutable grid coordinate usable as a set or dictionary key.
# Requires: import dataclasses
@dataclasses.dataclass(frozen=True)
class Point:
    # frozen=True makes value objects immutable/hashable if
    # fields are hashable.
    row: int
    col: int




# Task compares by priority and then name because dataclass order follows field order.
# Requires: import dataclasses
@dataclasses.dataclass(order=True)
class Task:
    # order=True makes comparisons use fields in definition order.
    priority: int
    name: str
    tags: list[str] = dataclasses.field(default_factory=list)




# TrieNode stores outgoing character edges and whether a complete word ends here.
# Requires: import dataclasses
@dataclasses.dataclass
# Requires via helper: import dataclasses
class TrieNode:
    children: dict[str, "TrieNode"] = dataclasses.field(
        default_factory=dict
    )
    is_word: bool = False


# Trie, also called a prefix tree, stores words by shared character prefixes.
class Trie:
    # Initializes a new instance and establishes its invariants.
    def __init__(self) -> None:
        self.root = TrieNode()

    # insert creates missing prefix nodes and marks the final node as a word.
    def insert(self, word: str) -> None:
        node = self.root
        for ch in word:
            node = node.children.setdefault(ch, TrieNode())
        node.is_word = True

    # search requires every character edge and an end-of-word marker.
    def search(self, word: str) -> bool:
        node = self.root
        for ch in word:
            if ch not in node.children:
                return False
            node = node.children[ch]
        return node.is_word


# Object notes:
#   `is` checks identity; `==` checks value equality.
#   Mutable class variables are shared by every instance; use
#   `self.x` in __init__.
#   `dataclasses.field(default_factory=list)` gives every dataclass
#   instance a fresh list.

# ====================================================================
# 10. Algorithm Skeletons
# ====================================================================

# Returns two indices whose values sum to target, or None. A map stores prior values. Time O(n),
# space O(n).
def two_sum_indices_using_map(
    nums: list[int], target: int
) -> tuple[int, int] | None:
    seen: dict[int, int] = {}
    for i, x in enumerate(nums):
        if target - x in seen:
            return seen[target - x], i
        seen[x] = i
    return None


# Requires ascending input and moves inward based on whether the sum is too small or large. Time
# O(n), space O(1).
def sorted_two_sum_indices_using_two_pointers(
    nums: list[int], target: int
) -> tuple[int, int] | None:
    left, right = 0, len(nums) - 1
    while left < right:
        total = nums[left] + nums[right]
        if total == target:
            return left, right
        if total < target:
            left += 1
        else:
            right -= 1
    return None




# Counts contiguous subarrays with at most k distinct values. The window shrinks until valid.
# Time O(n), space O(k).
# Requires: import collections
def count_subarrays_with_at_most_k_distinct_values(nums: list[int], k: int) -> int:
    if k < 0:
        return 0
    count: collections.defaultdict[int, int]
    count = collections.defaultdict(int)
    left = total = 0
    for right, x in enumerate(nums):
        count[x] += 1
        while len(count) > k:
            y = nums[left]
            count[y] -= 1
            if count[y] == 0:
                del count[y]
            left += 1
        total += right - left + 1
    return total


# Returns the first sorted index whose value is at least target, possibly len(nums). Time O(log
# n).
def first_index_at_least_target(nums: list[int], target: int) -> int:
    left, right = 0, len(nums)
    while left < right:
        mid = (left + right) // 2
        if nums[mid] < target:
            left = mid + 1
        else:
            right = mid
    return left


# Requires a monotonic predicate and returns its first true value in the search range. Time
# O(log range) predicate calls.
def smallest_feasible_value_using_binary_search(low: int, high: int, can) -> int:
    while low < high:
        mid = (low + high) // 2
        if is_feasible(mid):
            high = mid
        else:
            low = mid + 1
    return low




# Counts contiguous subarrays summing to target by matching earlier prefix sums. Time O(n),
# space O(n).
# Requires: import collections
def count_subarrays_with_target_sum_using_prefix_sums(nums: list[int], k: int) -> int:
    seen: collections.defaultdict[int, int] = collections.defaultdict(
        int
    )
    seen[0] = 1
    prefix = result = 0
    for x in nums:
        prefix += x
        result += seen[prefix - k]
        seen[prefix] += 1
    return result




# Returns the fewest edges from start to target in an unweighted graph, or -1. Time O(vertices +
# edges).
# Requires: import collections
def shortest_path_length_unweighted_breadth_first_search(
    graph: dict[int, list[int]], start: int, target: int
) -> int:
    q = collections.deque([(start, 0)])
    seen = {start}
    while q:
        node, dist = q.popleft()
        if node == target:
            return dist
        for neighbor in graph.get(node, []):
            if neighbor not in seen:
                seen.add(neighbor)
                q.append((neighbor, dist + 1))
    return -1




# Yields valid up, down, left, and right grid coordinates without diagonals.
# Requires: import collections.abc
def four_way_grid_neighbors(
    r: int, c: int, rows: int, cols: int
) -> collections.abc.Iterable[tuple[int, int]]:
    for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        nr, nc = r + dr, c + dc
        if 0 <= nr < rows and 0 <= nc < cols:
            yield nr, nc


# Counts four-directionally connected groups of 1 cells and mutates visited cells to 0. Time
# O(rows * columns).
# Requires via helper: import collections.abc
def count_islands_using_depth_first_search(grid: list[list[str]]) -> int:
    rows, cols = len(grid), len(grid[0]) if grid else 0

    # visit_connected_land marks every land cell connected to this cell.
    def visit_connected_land(r: int, c: int) -> None:
        if not (0 <= r < rows and 0 <= c < cols) or grid[r][c] != "1":
            return
        grid[r][c] = "0"
        for nr, nc in four_way_grid_neighbors(r, c, rows, cols):
            visit_connected_land(nr, nc)

    count = 0
    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == "1":
                count += 1
                visit_connected_land(r, c)
    return count


# Returns the power set. The path stores current choices and is copied before backtracking.
# Output O(n * 2^n).
def all_subsets_using_backtracking(nums: list[int]) -> list[list[int]]:
    result: list[list[int]] = []
    path: list[int] = []

    # backtrack chooses one candidate, explores it, then undoes that choice.
    def build_subsets(start: int) -> None:
        result.append(path.copy())
        for i in range(start, len(nums)):
            path.append(nums[i])
            build_subsets(i + 1)
            path.pop()

    build_subsets(0)
    return result


# Returns the next strictly greater index to the right, or -1. The stack stores unresolved
# indices. Time O(n).
def next_greater_index_using_monotonic_stack(nums: list[int]) -> list[int]:
    result = [-1] * len(nums)
    stack: list[int] = []  # indexes; decreasing values
    for i, x in enumerate(nums):
        while stack and nums[stack[-1]] < x:
            result[stack.pop()] = i
        stack.append(i)
    return result


# Sorts closed intervals and combines overlaps. Time O(n log n), output O(n).
def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:
    intervals.sort(key=lambda x: x[0])
    merged: list[list[int]] = []
    for start, end in intervals:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    return merged




# Returns k most frequent values using a size-k minimum heap. Time O(n log k), space O(n).
# Requires: import collections
# Requires: import heapq
def top_k_frequent_values_using_heap(nums: list[int], k: int) -> list[int]:
    counts = collections.Counter(nums)
    return [
        num
        for _, num in heapq.nlargest(
            k, ((freq, num) for num, freq in counts.items())
        )
    ]




# Returns the fewest coins totaling amount, or -1, using memoized recursion.
# Requires: import functools
def minimum_coins_top_down_dynamic_programming(coins: tuple[int, ...], amount: int) -> int:
    inf = amount + 1

    # minimum_coins_remaining memoizes the best answer for each remaining amount.
    # Requires: import functools
    @functools.cache
    def minimum_coins_remaining(remaining: int) -> int:
        if remaining == 0:
            return 0
        if remaining < 0:
            return inf
        return 1 + min(minimum_coins_remaining(remaining - coin) for coin in coins)

    result = minimum_coins_remaining(amount)
    return -1 if result >= inf else result


# Disjoint-set union, also called union-find, tracks connected groups with path compression and
# size-balanced merging.
class DisjointSetUnion:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, n: int) -> None:
        self.parent = list(range(n))
        self.size = [1] * n
        self.components = n

    # find returns the group representative and shortens future paths.
    def find(self, x: int) -> int:
        if self.parent[x] != x:
            self.parent[x] = self.find(self.parent[x])
        return self.parent[x]

    # union merges two groups by size and reports whether a merge occurred.
    def union(self, a: int, b: int) -> bool:
        root_a, root_b = self.find(a), self.find(b)
        if root_a == root_b:
            return False
        if self.size[root_a] < self.size[root_b]:
            root_a, root_b = root_b, root_a
        self.parent[root_b] = root_a
        self.size[root_a] += self.size[root_b]
        self.components -= 1
        return True

# ====================================================================
# 11. Sliding Windows, Two Pointers, and Palindromes
# ====================================================================

# Returns the longest substring with unique characters using a sliding set window. Time O(n).
def longest_substring_without_repeated_characters(s: str) -> int:
    seen: set[str] = set()
    left = best = 0
    for right, ch in enumerate(s):
        while ch in seen:
            seen.remove(s[left])
            left += 1
        seen.add(ch)
        best = max(best, right - left + 1)
    return best




# Requires non-negative values and returns the shortest window reaching target, or 0. Time O(n).
# Requires: import math
def minimum_subarray_length_with_sum_at_least_target(nums: list[int], target: int) -> int:
    left = total = 0
    best = math.inf
    for right, x in enumerate(nums):
        total += x
        while total >= target:
            best = min(best, right - left + 1)
            total -= nums[left]
            left += 1
    return 0 if best == math.inf else int(best)


# Returns the largest sum of exactly k contiguous values by adding one and removing one per
# step. Time O(n).
def maximum_sum_fixed_length_window(nums: list[int], k: int) -> int:
    window = sum(nums[:k])
    best = window
    for right in range(k, len(nums)):
        window += nums[right] - nums[right - k]
        best = max(best, window)
    return best




# Uses exactly(k) = at_most(k) - at_most(k-1). Time O(n), space O(k).
# Requires via helper: import collections
def count_subarrays_with_exactly_k_distinct_values(nums: list[int], k: int) -> int:
    return count_subarrays_with_at_most_k_distinct_values(
        nums, k
    ) - count_subarrays_with_at_most_k_distinct_values(nums, k - 1)


# Returns unique triples summing to zero after sorting and scanning with two pointers. Time
# O(n^2).
def unique_triplets_summing_to_zero(nums: list[int]) -> list[list[int]]:
    nums.sort()
    result: list[list[int]] = []
    for i, x in enumerate(nums):
        if i > 0 and x == nums[i - 1]:
            continue
        left, right = i + 1, len(nums) - 1
        while left < right:
            total = x + nums[left] + nums[right]
            if total == 0:
                result.append([x, nums[left], nums[right]])
                left += 1
                right -= 1
                while left < right and nums[left] == nums[left - 1]:
                    left += 1
                while left < right and nums[right] == nums[right + 1]:
                    right -= 1
            elif total < 0:
                left += 1
            else:
                right -= 1
    return result


# Moves zeros to the end in place while preserving non-zero order. Time O(n), space O(1).
def move_zeroes(nums: list[int]) -> None:
    write = 0
    for read, x in enumerate(nums):
        if x != 0:
            nums[write], nums[read] = nums[read], nums[write]
            write += 1


# Returns the largest water-container area; moving the shorter wall is the only move that can
# improve height. Time O(n).
def maximum_water_container_area_using_two_pointers(height: list[int]) -> int:
    left, right = 0, len(height) - 1
    best = 0
    while left < right:
        best = max(
            best, (right - left) * min(height[left], height[right])
        )
        if height[left] < height[right]:
            left += 1
        else:
            right -= 1
    return best


# Counts palindromic substrings by expanding around every character and gap. Time O(n^2).
def count_palindromic_substrings_by_expanding_centers(s: str) -> int:
    # expand counts palindromes sharing the supplied center.
    def count_from_center(left: int, right: int) -> int:
        count = 0
        while 0 <= left and right < len(s) and s[left] == s[right]:
            count += 1
            left -= 1
            right += 1
        return count

    return sum(count_from_center(i, i) + count_from_center(i, i + 1) for i in range(len(s)))

# ====================================================================
# 12. Strings and Advanced Binary Search
# ====================================================================

# Keeps alphanumeric characters, lowercases them, and removes punctuation and spaces.
def normalize_letters_and_digits_lowercase(s: str) -> str:
    return "".join(ch.lower() for ch in s if ch.isalnum())


# Checks a case-insensitive palindrome while skipping non-alphanumeric characters. Time O(n).
def is_palindrome_ignoring_non_letters_and_digits(s: str) -> bool:
    left, right = 0, len(s) - 1
    while left < right:
        while left < right and not s[left].isalnum():
            left += 1
        while left < right and not s[right].isalnum():
            right -= 1
        if s[left].lower() != s[right].lower():
            return False
        left += 1
        right -= 1
    return True


# Adds non-negative decimal integers represented as strings using right-to-left carry.
def add_decimal_strings(a: str, b: str) -> str:
    i, j, carry = len(a) - 1, len(b) - 1, 0
    result: list[str] = []
    while i >= 0 or j >= 0 or carry:
        x = ord(a[i]) - ord("0") if i >= 0 else 0
        y = ord(b[j]) - ord("0") if j >= 0 else 0
        carry, digit = divmod(x + y + carry, 10)
        result.append(chr(ord("0") + digit))
        i -= 1
        j -= 1
    return "".join(reversed(result))


# Compares dot-separated integer components and treats missing trailing components as zero.
def compare_version_numbers(version1: str, version2: str) -> int:
    a = [int(part) for part in version1.split(".")]
    b = [int(part) for part in version2.split(".")]
    n = max(len(a), len(b))
    for i in range(n):
        x = a[i] if i < len(a) else 0
        y = b[i] if i < len(b) else 0
        if x != y:
            return -1 if x < y else 1
    return 0


# Returns consecutive character runs as (character, count) pairs. Time O(n).
def run_length_encode(s: str) -> list[tuple[str, int]]:
    if not s:
        return []
    groups: list[tuple[str, int]] = []
    cur, count = s[0], 1
    for ch in s[1:]:
        if ch == cur:
            count += 1
        else:
            groups.append((cur, count))
            cur, count = ch, 1
    groups.append((cur, count))
    return groups


# Finds target in a distinct ascending array rotated at an unknown pivot. Time O(log n).
def search_rotated_sorted_array(nums: list[int], target: int) -> int:
    left, right = 0, len(nums) - 1
    while left <= right:
        mid = (left + right) // 2
        if nums[mid] == target:
            return mid
        if nums[left] <= nums[mid]:
            if nums[left] <= target < nums[mid]:
                right = mid - 1
            else:
                left = mid + 1
        else:
            if nums[mid] < target <= nums[right]:
                left = mid + 1
            else:
                right = mid - 1
    return -1




# Binary-searches a partition where every left value is at most every right value. Time O(log
# min(m, n)).
# Requires: import math
def median_of_two_sorted_arrays_using_partition(a: list[int], b: list[int]) -> float:
    if len(a) > len(b):
        a, b = b, a
    m, n = len(a), len(b)
    half = (m + n + 1) // 2
    left, right = 0, m
    while left <= right:
        i = (left + right) // 2
        j = half - i
        left1 = -math.inf if i == 0 else a[i - 1]
        right1 = math.inf if i == m else a[i]
        left2 = -math.inf if j == 0 else b[j - 1]
        right2 = math.inf if j == n else b[j]
        if left1 <= right2 and left2 <= right1:
            if (m + n) % 2:
                return float(max(left1, left2))
            return (max(left1, left2) + min(right1, right2)) / 2
        if left1 > right2:
            right = i - 1
        else:
            left = i + 1
    raise ValueError("inputs must be sorted")

# ====================================================================
# 13. Hashing, Prefix Sums, and Intervals
# ====================================================================

# Groups lowercase words by their 26-letter frequency tuple. Time O(total characters).
# Requires: import collections
def group_anagrams_by_letter_counts(words: list[str]) -> list[list[str]]:
    groups: collections.defaultdict[tuple[int, ...], list[str]]
    groups = collections.defaultdict(list)
    for word in words:
        count = [0] * 26
        for ch in word:
            count[ord(ch) - ord("a")] += 1
        groups[tuple(count)].append(word)
    return list(groups.values())


# Starts only where predecessor is absent, so each set value is visited once. Expected time
# O(n).
def longest_consecutive_sequence_length(nums: list[int]) -> int:
    values = set(nums)
    best = 0
    for x in values:
        if x - 1 not in values:
            y = x
            while y in values:
                y += 1
            best = max(best, y - x)
    return best


# Stores cumulative sums with a leading zero for constant-time inclusive range queries.
class OneDimensionalPrefixSum:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, nums: list[int]) -> None:
        self.prefix = [0]
        for x in nums:
            self.prefix.append(self.prefix[-1] + x)

    # sum_range returns the inclusive left-through-right sum in O(1).
    def sum_range(self, left: int, right: int) -> int:
        return self.prefix[right + 1] - self.prefix[left]


# Stores cumulative rectangle sums with a zero border for constant-time region queries.
class TwoDimensionalPrefixSum:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, matrix: list[list[int]]) -> None:
        rows = len(matrix)
        cols = len(matrix[0]) if matrix else 0
        self.prefix = [[0] * (cols + 1) for _ in range(rows + 1)]
        for r in range(rows):
            for c in range(cols):
                self.prefix[r + 1][c + 1] = (
                    matrix[r][c]
                    + self.prefix[r][c + 1]
                    + self.prefix[r + 1][c]
                    - self.prefix[r][c]
                )

    # sum_region returns an inclusive rectangle sum in O(1).
    def sum_region(self, r1: int, c1: int, r2: int, c2: int) -> int:
        return (
            self.prefix[r2 + 1][c2 + 1]
            - self.prefix[r1][c2 + 1]
            - self.prefix[r2 + 1][c1]
            + self.prefix[r1][c1]
        )


# Returns the maximum overlap of half-open meeting intervals. Time O(n log n).
def maximum_concurrent_meetings_using_two_pointers(intervals: list[list[int]]) -> int:
    starts = sorted(start for start, _ in intervals)
    ends = sorted(end for _, end in intervals)
    rooms = best = 0
    s = e = 0
    while s < len(starts):
        if starts[s] < ends[e]:
            rooms += 1
            best = max(best, rooms)
            s += 1
        else:
            rooms -= 1
            e += 1
    return best


# Inserts into sorted non-overlapping closed intervals and merges every overlap. Time O(n).
def insert_interval(
    intervals: list[list[int]], new_interval: list[int]
) -> list[list[int]]:
    result: list[list[int]] = []
    i = 0
    while i < len(intervals) and intervals[i][1] < new_interval[0]:
        result.append(intervals[i])
        i += 1
    while i < len(intervals) and intervals[i][0] <= new_interval[1]:
        new_interval[0] = min(new_interval[0], intervals[i][0])
        new_interval[1] = max(new_interval[1], intervals[i][1])
        i += 1
    return result + [new_interval] + intervals[i:]




# Greedily keeps earliest-ending intervals and returns minimum removals. Time O(n log n).
# Requires: import math
def erase_overlap_intervals(intervals: list[list[int]]) -> int:
    intervals.sort(key=lambda x: x[1])
    removed = 0
    prev_end = -math.inf
    for start, end in intervals:
        if start >= prev_end:
            prev_end = end
        else:
            removed += 1
    return removed

# ====================================================================
# 14. Linked-List Patterns
# ====================================================================

# Reuses nodes from two ascending linked lists to form one ascending list. Time O(a + b).
def merge_two_lists(
    a: ListNode | None, b: ListNode | None
) -> ListNode | None:
    dummy = tail = ListNode()
    while a and b:
        if a.val <= b.val:
            tail.next, a = a, a.next
        else:
            tail.next, b = b, b.next
        tail = tail.next
    tail.next = a or b
    return dummy.next


# Reverses a singly linked list in place. Time O(n), space O(1).
def reverse_list(head: ListNode | None) -> ListNode | None:
    prev = None
    cur = head
    while cur:
        next_node = cur.next
        cur.next = prev
        prev = cur
        cur = next_node
    return prev


# Uses Floyd slow/fast pointers; meeting proves a cycle. Time O(n), space O(1).
def linked_list_has_cycle_using_floyd_algorithm(head: ListNode | None) -> bool:
    slow = fast = head
    while fast and fast.next:
        slow = slow.next
        fast = fast.next.next
        if slow is fast:
            return True
    return False


# Keeps two pointers n nodes apart and removes the requested node in one pass.
def remove_nth_linked_list_node_from_end(
    head: ListNode | None, n: int
) -> ListNode | None:
    dummy = ListNode(0, head)
    fast = slow = dummy
    for _ in range(n):
        fast = fast.next
    while fast and fast.next:
        fast = fast.next
        slow = slow.next
    if slow.next:
        slow.next = slow.next.next
    return dummy.next

# ====================================================================
# 15. Least-Recently-Used Cache Design
# ====================================================================

# CacheNode stores one cache entry plus links in the recency list.
class CacheNode:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, key: int = 0, val: int = 0) -> None:
        self.key = key
        self.val = val
        self.prev: CacheNode | None = None
        self.next: CacheNode | None = None


# Least-recently-used cache using a map plus doubly linked recency list for O(1) operations.
class LeastRecentlyUsedCacheDoublyLinkedList:
    # Initializes a new instance and establishes its invariants.
    def __init__(self, capacity: int) -> None:
        self.capacity = capacity
        self.nodes: dict[int, CacheNode] = {}
        self.head = CacheNode()
        self.tail = CacheNode()
        self.head.next = self.tail
        self.tail.prev = self.head

    # Internal helper for remove.
    def _remove(self, node: CacheNode) -> None:
        prev, next_node = node.prev, node.next
        assert prev is not None and next_node is not None
        prev.next = next_node
        next_node.prev = prev

    # Internal helper for add to back.
    def _add_to_back(self, node: CacheNode) -> None:
        prev = self.tail.prev
        assert prev is not None
        node.prev, node.next = prev, self.tail
        prev.next = self.tail.prev = node

    # get returns a cached value and marks its entry most recently used.
    def get(self, key: int) -> int:
        if key not in self.nodes:
            return -1
        node = self.nodes[key]
        self._remove(node)
        self._add_to_back(node)
        return node.val

    # put inserts or updates a value and evicts the least recent entry when full.
    def put(self, key: int, value: int) -> None:
        if key in self.nodes:
            self._remove(self.nodes[key])
        node = CacheNode(key, value)
        self.nodes[key] = node
        self._add_to_back(node)
        if len(self.nodes) > self.capacity:
            victim = self.head.next
            assert victim is not None and victim is not self.tail
            self._remove(victim)
            del self.nodes[victim.key]




# Least-recently-used cache using OrderedDict recency operations in O(1).
# Requires: import collections
class LeastRecentlyUsedCacheOrderedDictionary:
    # Initializes a new instance and establishes its invariants.
    # Requires: import collections
    def __init__(self, capacity: int) -> None:
        self.capacity = capacity
        self.data: collections.OrderedDict[int, int]
        self.data = collections.OrderedDict()

    # get returns a cached value and marks its entry most recently used.
    def get(self, key: int) -> int:
        if key not in self.data:
            return -1
        self.data.move_to_end(key)
        return self.data[key]

    # put inserts or updates a value and evicts the least recent entry when full.
    def put(self, key: int, value: int) -> None:
        if key in self.data:
            self.data.move_to_end(key)
        self.data[key] = value
        if len(self.data) > self.capacity:
            self.data.popitem(last=False)

# ====================================================================
# 16. Trees, Graphs, and Shortest Paths
# ====================================================================

# Returns tree values grouped by depth using a queue. Time O(nodes).
# Requires: import collections
def binary_tree_values_by_level_breadth_first_search(root: TreeNode | None) -> list[list[int]]:
    if root is None:
        return []
    result: list[list[int]] = []
    q = collections.deque([root])
    while q:
        level: list[int] = []
        for _ in range(len(q)):
            node = q.popleft()
            level.append(node.val)
            if node.left:
                q.append(node.left)
            if node.right:
                q.append(node.right)
        result.append(level)
    return result




# Returns four-way shortest distances through zero cells, leaving unreachable cells as -1.
# Requires: import collections
# Requires via helper: import collections.abc
def grid_shortest_distances_using_breadth_first_search(
    grid: list[list[int]], start: tuple[int, int]
) -> list[list[int]]:
    rows, cols = len(grid), len(grid[0])
    dist = [[-1] * cols for _ in range(rows)]
    q = collections.deque([start])
    dist[start[0]][start[1]] = 0  # Mark on enqueue, not on pop.
    while q:
        r, c = q.popleft()
        for nr, nc in four_way_grid_neighbors(r, c, rows, cols):
            if grid[nr][nc] == 0 and dist[nr][nc] == -1:
                dist[nr][nc] = dist[r][c] + 1
                q.append((nr, nc))
    return distances




# Kahn algorithm repeatedly removes zero-in-degree nodes; returns [] when a directed cycle
# remains.
# Requires: import collections
def topological_order_using_kahn_algorithm(
    n: int, edges: list[tuple[int, int]]
) -> list[int]:
    graph: collections.defaultdict[int, list[int]]
    graph = collections.defaultdict(list)
    in_degree = [0] * n
    for pre, course in edges:
        graph[pre].append(course)
        in_degree[course] += 1
    q = collections.deque(
        i for i, deg in enumerate(in_degree) if deg == 0
    )
    order: list[int] = []
    while q:
        node = q.popleft()
        order.append(node)
        for neighbor in graph[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                q.append(neighbor)
    return order if len(order) == n else []




# Returns shortest distances for non-negative weighted edges using a minimum heap. Time O((V +
# E) log V).
# Requires: import heapq
# Requires: import math
def shortest_distances_using_dijkstra_algorithm(
    graph: dict[int, list[tuple[int, int]]], start: int
) -> dict[int, int]:
    dist: dict[int, int] = {start: 0}
    heap = [(0, start)]
    while heap:
        distance, node = heapq.heappop(heap)
        if distance != distances[node]:
            continue
        for neighbor, weight in graph.get(node, []):
            next_distance = distance + weight
            if nd < dist.get(neighbor, math.inf):
                distances[neighbor] = next_distance
                heapq.heappush(heap, (next_distance, neighbor))
    return distances

# ====================================================================
# 17. Stacks and Heap-Based Merging
# ====================================================================

# Checks that round, square, and curly brackets close in last-in-first-out order.
def has_valid_bracket_nesting(s: str) -> bool:
    close_to_open = {")": "(", "]": "[", "}": "{"}
    stack: list[str] = []
    for ch in s:
        if ch in close_to_open.values():
            stack.append(ch)
        elif ch in close_to_open:
            if not stack or stack.pop() != close_to_open[ch]:
                return False
    return not stack


# Stores each value beside the minimum at that depth for O(1) minimum queries.
class StackWithMinimum:
    # Initializes a new instance and establishes its invariants.
    def __init__(self) -> None:
        self.stack: list[tuple[int, int]] = []

    # push stores the value and the minimum at this new stack depth.
    def push(self, val: int) -> None:
        cur_min = (
            val if not self.stack else min(val, self.stack[-1][1])
        )
        self.stack.append((val, cur_min))

    # pop removes and returns the newest value.
    def pop(self) -> int:
        return self.stack.pop()[0]

    # top returns the newest value without removing it.
    def top(self) -> int:
        return self.stack[-1][0]

    # get_min returns the current minimum without scanning the stack.
    def get_min(self) -> int:
        return self.stack[-1][1]




# Performs a k-way merge by storing one current value from each sorted array. Time O(total log
# k).
# Requires: import heapq
def merge_sorted_arrays_using_min_heap(arrays: list[list[int]]) -> list[int]:
    heap: list[tuple[int, int, int]] = []
    for arr_i, arr in enumerate(arrays):
        if arr:
            heapq.heappush(heap, (arr[0], arr_i, 0))
    result: list[int] = []
    while heap:
        val, arr_i, elem_i = heapq.heappop(heap)
        result.append(val)
        next_node = elem_i + 1
        if next_node < len(arrays[arr_i]):
            heapq.heappush(heap, (arrays[arr_i][next_node], arr_i, next_node))
    return result

# ====================================================================
# 18. Dynamic Programming and Backtracking
# ====================================================================

# Kadane algorithm keeps the best sum ending at each position. Time O(n), space O(1).
def maximum_subarray_sum_using_kadane_algorithm(nums: list[int]) -> int:
    best = best_ending_here = nums[0]
    for x in nums[1:]:
        best_ending_here = max(x, best_ending_here + x)
        best = max(best, best_ending_here)
    return best


# Counts one- or two-step sequences while retaining only the previous two dynamic-programming
# states.
def count_ways_to_climb_stairs_using_rolling_state(n: int) -> int:
    if n <= 2:
        return n
    prev2, prev1 = 1, 2
    for _ in range(3, n + 1):
        prev2, prev1 = prev1, prev1 + prev2
    return prev1


# Returns the longest sequence obtainable without reordering either string. Time and space O(m *
# n).
def longest_common_subsequence_length(a: str, b: str) -> int:
    dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]
    for i in range(len(a) - 1, -1, -1):
        for j in range(len(b) - 1, -1, -1):
            dp[i][j] = (
                1 + dp[i + 1][j + 1]
                if a[i] == b[j]
                else max(dp[i + 1][j], dp[i][j + 1])
            )
    return dp[0][0]


# Uses zero-or-one knapsack state to test whether values split into equal sums.
def can_partition_into_equal_sum_subsets(nums: list[int]) -> bool:
    total = sum(nums)
    if total % 2:
        return False
    target = total // 2
    possible = [False] * (target + 1)
    possible[0] = True
    for x in nums:
        for candidate_sum in range(target, x - 1, -1):
            possible[candidate_sum] = (
                possible[candidate_sum]
                or possible[candidate_sum - x]
            )
    return possible[target]


# Returns every ordering by choosing unused positions and undoing each choice. Output O(n * n!).
def all_permutations_using_backtracking(nums: list[int]) -> list[list[int]]:
    result: list[list[int]] = []
    path: list[int] = []
    used = [False] * len(nums)

    # backtrack chooses one candidate, explores it, then undoes that choice.
    def build_permutations() -> None:
        if len(path) == len(nums):
            result.append(path.copy())
            return
        for i, x in enumerate(nums):
            if used[i]:
                continue
            used[i] = True
            path.append(x)
            build_permutations()
            path.pop()
            used[i] = False

    build_permutations()
    return result


# Returns target-sum combinations where positive candidates may be reused and ordering is
# ignored.
def combinations_summing_to_target_with_reuse(
    candidates: list[int], target: int
) -> list[list[int]]:
    candidates.sort()
    result: list[list[int]] = []
    path: list[int] = []

    # backtrack chooses one candidate, explores it, then undoes that choice.
    def build_combinations(start: int, remaining: int) -> None:
        if remaining == 0:
            result.append(path.copy())
            return
        for i in range(start, len(candidates)):
            x = candidates[i]
            if x > remaining:
                break
            path.append(x)
            build_combinations(i, remaining - x)
            path.pop()

    build_combinations(0, target)
    return result

# ====================================================================
# 19. Math, Primes, and Parsing
# ====================================================================

# Returns decimal digits from most significant to least significant.
def base10_digits(n: int) -> list[int]:
    n = abs(n)
    if n == 0:
        return [0]
    digits: list[int] = []
    while n:
        n, digit = divmod(n, 10)
        digits.append(digit)
    return digits[::-1]




# Builds an integer from decimal digits and rejects values outside 0 through 9.
# Requires: import collections.abc
def int_from_base10_digits(
    digits: collections.abc.Iterable[int],
) -> int:
    result = 0
    for digit in digits:
        result = result * 10 + digit
    return result




# Divides numerator and denominator by their greatest common divisor.
# Requires: import math
def reduce_fraction(
    numerator: int, denominator: int
) -> tuple[int, int]:
    g = math.gcd(numerator, denominator)
    numerator //= g
    denominator //= g
    if denominator < 0:
        numerator, denominator = -numerator, -denominator
    return numerator, denominator


# Tests possible divisors through the square root. Time O(sqrt(n)).
def is_prime_trial(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    factor = 3
    while factor * factor <= n:
        if n % factor == 0:
            return False
        factor += 2
    return True


# Sieve of Eratosthenes marks composite multiples and returns primality through n.
def sieve_is_prime(n: int) -> list[bool]:
    is_prime = [True] * (n + 1)
    if n >= 0:
        is_prime[0] = False
    if n >= 1:
        is_prime[1] = False
    p = 2
    while p * p <= n:
        if is_prime[p]:
            for multiple in range(p * p, n + 1, p):
                is_prime[multiple] = False
        p += 1
    return is_prime


# Returns each prime factor mapped to its exponent using trial division.
def prime_factor_counts(n: int) -> dict[int, int]:
    n = abs(n)
    factors: dict[int, int] = {}
    divisor = 2
    while divisor * divisor <= n:
        while n % divisor == 0:
            factors[divisor] = factors.get(divisor, 0) + 1
            n //= divisor
        divisor += 1 if divisor == 2 else 2
    if n > 1:
        factors[n] = factors.get(n, 0) + 1
    return factors


# Assumes all values occur twice except one; exclusive OR cancels equal pairs.
def single_number_xor(nums: list[int]) -> int:
    result = 0
    for x in nums:
        result ^= x
    return result


# Reverses decimal digits and returns 0 when the signed 32-bit range would overflow.
def reverse_integer_32(x: int) -> int:
    sign = -1 if x < 0 else 1
    x = abs(x)
    limit = 2**31 - 1 if sign > 0 else 2**31
    result = 0
    while x:
        digit = x % 10
        x //= 10
        if result > limit // 10 or (
            result == limit // 10 and digit > limit % 10
        ):
            return 0
        result = result * 10 + digit
    return sign * result


# Parses optional sign and decimal digits, clamping to the signed 32-bit range.
def parse_signed_int32_clamped(s: str) -> int:
    i = 0
    while i < len(s) and s[i] == " ":
        i += 1
    sign = 1
    if i < len(s) and s[i] in "+-":
        sign = -1 if s[i] == "-" else 1
        i += 1
    result = 0
    while i < len(s) and s[i].isdigit():
        result = result * 10 + int(s[i])
        i += 1
    return max(-(2**31), min(2**31 - 1, sign * result))


# Checks whether digit runs skip exactly the stated number of word characters.
def valid_word_abbreviation(word: str, abbr: str) -> bool:
    i = j = 0
    while i < len(abbr):
        if j >= len(word):
            return False
        if abbr[i] == word[j]:
            i += 1
            j += 1
        elif not abbr[i].isdigit() or abbr[i] == "0":
            return False
        else:
            skip = 0
            while i < len(abbr) and abbr[i].isdigit():
                skip = skip * 10 + int(abbr[i])
                i += 1
            j += skip
    return j == len(word)


# Parses a comma-separated transaction into typed fields after validating field count.
def parse_transaction_record(raw: str) -> tuple[str, int, int, str]:
    name, time, amount, city = raw.split(",")
    return name, int(time), int(amount), city

# ====================================================================
# 20. Matrix Simulation and Recursion Limits
# ====================================================================

# Compacts non-zero matrix values downward within each column.
def apply_gravity(board: list[list[int]]) -> None:
    rows, cols = len(board), len(board[0])
    for c in range(cols):
        write = rows - 1
        for r in range(rows - 1, -1, -1):
            if board[r][c] != 0:
                board[write][c] = board[r][c]
                write -= 1
        for r in range(write, -1, -1):
            board[r][c] = 0


# Returns the first coordinate starting three equal non-zero values in a row.
def find_three_in_a_row(
    board: list[list[int]],
) -> set[tuple[int, int]]:
    rows, cols = len(board), len(board[0])
    crush: set[tuple[int, int]] = set()
    for r in range(1, rows - 1):
        for c in range(cols):
            if (
                board[r][c]
                and board[r - 1][c] == board[r][c] == board[r + 1][c]
            ):
                crush.update({(r - 1, c), (r, c), (r + 1, c)})
    for r in range(rows):
        for c in range(1, cols - 1):
            if (
                board[r][c]
                and board[r][c - 1] == board[r][c] == board[r][c + 1]
            ):
                crush.update({(r, c - 1), (r, c), (r, c + 1)})
    return crush




# Raises Python recursion depth for unusually deep recursive traversal; use carefully because
# stack memory still grows.
# Requires: import sys
def raise_recursion_limit_for_deep_depth_first_search() -> None:
    sys.setrecursionlimit(10**6)

# ====================================================================
# 21. Main Guard and Executable Checks
# ====================================================================

# solve is a minimal local-script placeholder; LeetCode normally calls a
# method on Solution instead.
def solve(nums: list[int]) -> int:
    return sum(nums)


# assert_file_width fails when generated lines become too wide to scan
# comfortably. The 100-column limit leaves room for explanatory names.
def assert_file_width(max_columns: int = 100) -> None:
    with open(__file__, encoding="utf-8") as source:
        for line_no, line in enumerate(source, 1):
            text = line.rstrip("\n")
            width = len(text)
            if width <= max_columns:
                continue
            message = (
                f"line {line_no} is {width} columns "
                f"(limit {max_columns}): {text!r}"
            )
            raise AssertionError(message)


# run_smoke_checks exercises representative language and algorithm sections.
# These are integration checks for generation and renaming, not exhaustive
# correctness tests.
def run_smoke_checks() -> None:
    assert two_sum_indices_using_map([2, 7, 11], 9) == (0, 1)
    assert first_index_at_least_target([1, 3, 3, 8], 3) == 1
    assert count_subarrays_with_target_sum_using_prefix_sums(
        [1, 1, 1], 2
    ) == 2
    assert (
        shortest_path_length_unweighted_breadth_first_search(
            {0: [1], 1: [2], 2: []}, 0, 2
        )
        == 2
    )
    assert all_subsets_using_backtracking([1, 2]) == [
        [],
        [1],
        [1, 2],
        [2],
    ]
    assert unique_triplets_summing_to_zero(
        [-1, 0, 1, 2, -1, -4]
    ) == [[-1, -1, 2], [-1, 0, 1]]
    assert search_rotated_sorted_array([4, 5, 6, 0, 1, 2], 0) == 3
    assert longest_consecutive_sequence_length([100, 4, 2, 1, 3]) == 4
    assert maximum_subarray_sum_using_kadane_algorithm(
        [-2, 1, -3, 4, -1, 2, 1]
    ) == 6
    assert reduce_fraction(8, 12) == (2, 3)
    union_find = DisjointSetUnion(3)
    assert union_find.union(0, 1)
    assert union_find.find(0) == union_find.find(1)


# main runs the sample, smoke checks, and readability guard when this
# generated aggregate is executed as a local script.
def main() -> None:
    sample = [1, 2, 3]
    print(solve(sample))
    run_smoke_checks()
    assert_file_width()


if __name__ == "__main__":
    # LeetCode normally calls `Solution` methods directly, so do
    # not include this
    # in submissions unless you are building a local script or
    # template.
    main()
